apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: messaging-service
  name: messaging-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: messaging-service
    spec:
      containers:
      - image: nimbleplatform/messaging-service:IMAGE_TAG
        imagePullPolicy: Always
        name: messaging-service
        env:
        - name: CSB_URL
          value: "csb-kafka:8080"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 256Mi