apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: messaging-service
  name: messaging-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: messaging-service
    spec:
      containers:
      - image: nimbleplatform/messaging-service:IMAGE_TAG
        imagePullPolicy: Always
        name: messaging-service
        env:
        - name: CSB_URL
          value: "csb-kafka:8080"
        - name: SERVICE_URL
          value: "messaging-service:8080"
        - name: MESSAGING_TABLE
          value: "messaging_table_prod"
        - name: SESSIONS_TABLE
          value: "sessions_table_prod"
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: url
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
